import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { cp, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const root = process.cwd();
const output = path.join(root, "artifacts", `student-confirm-${Date.now()}`);
const fixture = path.join(output, "fixture");
let server, browser;
let logs = "";
try {
  await mkdir(path.join(fixture, "app"), { recursive: true });
  for (const dir of ["components", "lib", "tests/fixtures"]) await cp(path.join(root, dir), path.join(fixture, dir), { recursive: true });
  for (const file of ["package.json", "jsconfig.json", "app/globals.css", "app/book-sidebar.css"]) await cp(path.join(root, file), path.join(fixture, file));
  await writeFile(path.join(fixture, "app/page.jsx"), 'export { default } from "@/tests/fixtures/StudentConfirmGatePage";');
  await writeFile(path.join(fixture, "app/layout.jsx"), 'import "./globals.css"; import "./book-sidebar.css"; export default function Layout({children}) { return <html lang="ko"><body>{children}</body></html>; }');
  server = spawn(process.execPath, [require.resolve("next/dist/bin/next"), "dev", "--hostname", "127.0.0.1", "--port", "3249"], { cwd: fixture, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
  server.stdout.on("data", value => { logs += value; }); server.stderr.on("data", value => { logs += value; });
  const deadline = Date.now() + 120000;
  while (!logs.includes("Ready in")) { if (server.exitCode !== null || Date.now() > deadline) throw new Error(logs); await new Promise(resolve => setTimeout(resolve, 250)); }
  browser = await chromium.launch({ channel: "chrome", headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  page.setDefaultTimeout(60000);
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  await page.goto("http://127.0.0.1:3249");
  const cards = page.locator(".book-personal-detail-list > article");
  const first = cards.nth(0), second = cards.nth(1), resource = cards.nth(2);
  const confirm = card => card.locator("footer button").first();
  await confirm(first).waitFor();
  assert.equal(await confirm(first).textContent(), "미확인");
  assert.equal(await confirm(resource).textContent(), "미확인");
  assert(await confirm(first).isDisabled()); assert(await confirm(second).isDisabled()); assert(await confirm(resource).isDisabled());
  await first.getByRole("button", { name: "패널에서 열기" }).click();
  await page.waitForFunction(() => !document.querySelector('.book-personal-detail-list > article footer button').disabled);
  assert(await confirm(second).isDisabled());
  await page.getByRole("button", { name: "활동 패널 접기" }).click();
  assert(await confirm(first).isDisabled());
  await first.getByRole("button", { name: "패널에서 열기" }).click();
  const panel = page.getByRole("complementary", { name: "선택한 활동과 자료" });
  await panel.getByRole("textbox", { name: "답변 내용" }).fill("패널에서 작성한 아이디어");
  await panel.getByRole("button", { name: "저장", exact: true }).click();
  await first.getByRole("button", { name: "확인됨", exact: true }).waitFor();
  assert.equal(JSON.parse(await page.getByTestId("saved").textContent()).first, "패널에서 작성한 아이디어");
  assert.equal(await page.getByText("자동 저장됨", { exact: true }).count(), 0);
  await second.getByRole("button", { name: "활동 확대" }).click();
  const modal = page.getByRole("dialog");
  await modal.getByRole("textbox", { name: "답변 내용" }).fill("모달에서 작성한 기능");
  await modal.getByRole("button", { name: "저장", exact: true }).click();
  await second.getByRole("button", { name: "확인됨", exact: true }).waitFor();
  assert.equal(JSON.parse(await page.getByTestId("saved").textContent()).second, "모달에서 작성한 기능");
  assert.equal(await page.getByText("자동 저장됨", { exact: true }).count(), 0);
  await modal.waitFor({ state: "hidden" });
  await resource.getByRole("button", { name: "패널에서 열기" }).click();
  await page.waitForFunction(() => !document.querySelectorAll('.book-personal-detail-list > article footer button')[4].disabled);
  await confirm(resource).click();
  await resource.getByRole("button", { name: "확인됨", exact: true }).waitFor();
  for (const width of [375, 768, 1280]) { await page.setViewportSize({ width, height: 900 }); await page.screenshot({ path: path.join(output, `${width}.png`), fullPage: true }); }
  assert.deepEqual(errors, []);
  const teacher = page.getByTestId("teacher-card");
  await teacher.getByRole("button", { name: "활동 전", exact: true }).click();
  assert.equal(await teacher.getByRole("button", { name: "활동중", exact: true }).getAttribute("aria-pressed"), "true");
  await teacher.getByRole("button", { name: "활동중", exact: true }).click();
  assert.equal(await teacher.getByRole("button", { name: "활동 전", exact: true }).getAttribute("aria-pressed"), "false");
  console.log(`PASS: closed/matching/collapsed panel gating, panel and modal save confirmations, resources, no autosave message. ${output}`);
} finally {
  await browser?.close();
  if (server && server.exitCode === null) await new Promise(resolve => spawn("taskkill", ["/PID", String(server.pid), "/T", "/F"], { windowsHide: true }).on("close", resolve));
  await writeFile(path.join(output, "server.log"), logs);
}
